# By downloading or using this file, the user agrees to be bound by the terms of the license 
# agreement located in the LICENSE file in the root of this project
# as an original contracting party.
#
#  Description        :   Makefile for the OCAStm32F207xxOcaLite Board Support Package.
# 
TARGETS = stm32

TYPE = LIB
NAME = OCAStm32F207xxOcaLiteBsp

SRC_INC =

SRCS = OCAStm32F207xxOcaLite-reset.S 

include $(OCA_HOME)/Src/makeCpp.inc
