# By downloading or using this file, the user agrees to be bound by the terms of the license 
# agreement located at http://ocaalliance.com/EULA as an original contracting party.
#
#  Description        :   Makefile for Stm32CortexM3 
#

TARGETS = stm32

include $(OCA_HOME)/Src/makeMulti.inc

phony:
	@$(MAKE) -C "Board Support Packages" $(TARGET)
