# By downloading or using this file, the user agrees to be bound by the terms of the license 
# agreement located at http://ocaalliance.com/EULA as an original contracting party.
#
#  Description        :   Makefile for LogicalDevices
# 

TARGETS = winnt stmCortexM4

TYPE = LIB
NAME = LogicalDevices

USRINC = 
		 
USRDEFS = STM32F437xx

SRC_INC = ClockGenerator \
          Switch

SRCS = ClockGenerator.cpp \
       Switch.cpp

include $(OCA_HOME)/Src/makeCpp.inc
